### ISSUE TITLE
all v get_all

### ISSUE THREAD

**Issue by DavidWolff218** [learn-co-curriculum/python-p3-mapping-python-classes-to-a-database#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/mapping-database-records-to-python-objects?module_item_id=468023

### Concern

![Screen Shot 2023-01-02 at 12 50 41 PM](https://user-images.githubusercontent.com/60520496/210269497-ed015ed9-add6-48bf-9f5e-602d8f7c6f5e.png)

the function in the first screen shot is called all, then it is called get_all

**Comment by professor-ben** [comment]
Definitely a mistake. Working on this now.

**Comment by professor-ben** [comment]
This has been fixed in the blueprint and should be visible later today. Thanks for bringing this to our attention!

-Ben
