### ISSUE TITLE
Class method called with `self` parameter.

### ISSUE THREAD

**Issue by a-JAVA-chip-frappuccino** [learn-co-curriculum/python-p3-mapping-python-classes-to-a-database#5]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231365?module_item_id=541563

### Concern

This code in the instructions:

```
    @classmethod
    def create_table(self):
        sql = """
            CREATE TABLE IF NOT EXISTS songs (
                id INTEGER PRIMARY KEY,
                name TEXT,
                album TEXT
            )
        """

        CURSOR.execute(sql)
```

erroneously calls `self` as the parameter for a class method. This should likely say `cls`, I believe!

### Suggested Changes

Inside the `create_table` method, call `cls` rather than `self` to make it a class method.

**Comment by pgill97** [comment]
Changed function signature from self to cls.
