### ISSUE TITLE
Canvas Reading and README not in sync

### ISSUE THREAD

**Issue by baspin94** [learn-co-curriculum/python-p3-mapping-python-classes-to-a-database#6]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231365?module_item_id=541563

### Concern

It appears that additions were made to the code-along for this lesson within the README that do not show up in the lesson on Canvas. Some examples that are in the README but not Canvas:

- The solution code block starting at line 577.
- Code block starting at line 441 - in particular, line 452 -- CONN.commit() -- which is necessary for getting all tests to pass.

**Comment by professor-ben** [comment]
Thanks for bringing this to our attention! The script that syncs our changes to Canvas occasionally forgets to do its job. The most recent changes should be reflected in Canvas tomorrow morning.
